### ISSUE TITLE
[Errno 22] Invalid argument

### ISSUE THREAD

**Issue by aniloc111** [salaniz/pycocoevalcap#8]
![image](https://user-images.githubusercontent.com/5946900/81032741-86d38f00-8ec3-11ea-8ed7-eeffa49db374.png)

Hi, I face the same issue as what others have faced before and there's no solution presented. The issues are just closed immediately without telling how to fix the problem

**Comment by salaniz** [comment]
The previous threads were closed because the author was not responsive when I was trying to help. As of now I could not re-produce the problem.
Could you please do the following:
- Tell me more about your system: Which OS are you running? Which Python and which Java version are you using?
- Print the `score_line` variable right before the error occurs.
- Then follow the instructions I presented in issue https://github.com/salaniz/pycocoevalcap/issues/5#issuecomment-453943294, input the content of the variable you just printed and let me know what you see (outputs, errors).

**Comment by aniloc111** [comment]
> The previous threads were closed because the author was not responsive when I was trying to help. As of now I could not re-produce the problem.
> Could you please do the following:
> 
> * Tell me more about your system: Which OS are you running? Which Python and which Java version are you using?
> * Print the `score_line` variable right before the error occurs.
> * Then follow the instructions I presented in issue [#5 (comment)](https://github.com/salaniz/pycocoevalcap/issues/5#issuecomment-453943294), input the content of the variable you just printed and let me know what you see (outputs, errors).

Hi, I created an environment in Anaconda with Python 3.6
* OS: Windows 10
* Python version : Python 3.6
* Java version: 1.8.0_241

> Print the score_line variable right before the error occurs.
There are some results in the `score_line`. Here's a sample output
![image](https://user-images.githubusercontent.com/5946900/81082551-009c6480-8f26-11ea-9509-eae2ba782cbd.png)
![image](https://user-images.githubusercontent.com/5946900/81082648-21fd5080-8f26-11ea-9611-4e6b133802f8.png)


> Then follow the instructions I presented in issue #5 (comment), input the content of the variable you just printed and let me know what you see (outputs, errors).

From [#5 (comment)](https://github.com/salaniz/pycocoevalcap/issues/5#issuecomment-453943294)

> Could you navigate to the meteor directory (where meteor.py is located) and check that the following command executes without error: java -jar -Xmx2G meteor-1.5.jar - - -stdio -l en -norm

This is the output
![image](https://user-images.githubusercontent.com/5946900/81082943-85877e00-8f26-11ea-8312-7f62d8686470.png)

**Comment by salaniz** [comment]
The last output is the critical information here. Java crashes because it cannot allocate enough memory. You can try to change the `Xmx2G` parameter in the code based on how much memory you have available. You can use this stand alone command to test if it works with less memory. Alternatively, if you can, you could switch to a machine with more memory.

**Comment by aniloc111** [comment]
I changed the `Xmx2G` to `Xms256m` and the result is shown below.

![image](https://user-images.githubusercontent.com/5946900/81092048-9f2ec280-8f32-11ea-863f-cb9bb9e46b9b.png)

**Comment by salaniz** [comment]
This means that the `meteor-1.5.jar` requires more memory than `256m`.
I believe the `2G` was chosen by the original authors, because it is more or less required to run the program. If you don't have enough memory available, I am afraid you can't run it. You could consider using `pycocoevalcap` without `meteor` by removing this line https://github.com/salaniz/pycocoevalcap/blob/38c2534418237ba83809b925be2a8abbecdf2fa1/eval.py#L42 if that's an option.

**Comment by aniloc111** [comment]
Actually, I commented that line just to proceed with the training. 
Thanks @salaniz

**Comment by salaniz** [comment]
No problem. I am closing this issue then.

**Comment by Eom-taeseon** [comment]
@salaniz Hi! I hope you see this.

I have same problem, and tried same thing you suggested.

- Tell me more about your system: Which OS are you running? Which Python and which Java version are you using?
OS : windows10
python : python 3.8.12
Java : 1.8.0_311

- Print the score_line variable right before the error occurs.
![캡처](https://user-images.githubusercontent.com/37288329/141221127-6d925330-aed8-4eac-9b4b-1163e7aa8484.PNG)


- Then follow the instructions I presented in issue [Errno 22] Invalid argument for self.meteor_p.stdin.flush() #5 (comment), input the content of the variable you just printed and let me know what you see (outputs, errors).
This is what I've got problem.
![캡처](https://user-images.githubusercontent.com/37288329/141221255-bf7b9c5a-9c79-478d-be91-56389de35238.PNG)
I think I have enough memory, but still, it shows error.

What should I do?

**Comment by MrAccelerator** [comment]
> @salaniz Hi! I hope you see this.
> 
> I have same problem, and tried same thing you suggested.
> 
>     * Tell me more about your system: Which OS are you running? Which Python and which Java version are you using?
>       OS : windows10
>       python : python 3.8.12
>       Java : 1.8.0_311
> 
>     * Print the score_line variable right before the error occurs.
>       ![캡처](https://user-images.githubusercontent.com/37288329/141221127-6d925330-aed8-4eac-9b4b-1163e7aa8484.PNG)
> 
>     * Then follow the instructions I presented in issue [Errno 22] Invalid argument for self.meteor_p.stdin.flush() [[Errno 22] Invalid argument for self.meteor_p.stdin.flush() #5](https://github.com/salaniz/pycocoevalcap/issues/5) (comment), input the content of the variable you just printed and let me know what you see (outputs, errors).
>       This is what I've got problem.
>       ![캡처](https://user-images.githubusercontent.com/37288329/141221255-bf7b9c5a-9c79-478d-be91-56389de35238.PNG)
>       I think I have enough memory, but still, it shows error.
> 
> 
> What should I do?

Is your problem solved?
